// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Migrations
{
    [DbContext(typeof(RazorPagesContext))]
    [Migration("20190628230256_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RazorPagesMovie.Models.Assignment", b =>
                {
                    b.Property<int>("TechnicianID");

                    b.Property<int>("ProjectID");

                    b.Property<int>("ProjectID1");

                    b.HasKey("TechnicianID", "ProjectID");

                    b.HasAlternateKey("ProjectID", "TechnicianID");

                    b.HasIndex("ProjectID1");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedTechnicians");

                    b.Property<string>("Creator");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(360);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("PostulatedTechnicians");

                    b.Property<string>("RequiredSpecialization");

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Technician", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("Technician");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Assignment", b =>
                {
                    b.HasOne("RazorPagesMovie.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectID1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RazorPagesMovie.Models.Technician", "Technician")
                        .WithMany("Assignments")
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
